# Generated by Django 4.1.2 on 2022-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=150, unique=True, verbose_name='Url для категории'),
            preserve_default=False,
        ),
    ]
