# Generated by Django 4.1.2 on 2022-11-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
