# Generated by Django 4.1.2 on 2022-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telebotsettings',
            name='telegram_message',
            field=models.TextField(verbose_name='Макет сообщения'),
        ),
    ]
