# Generated by Django 4.1.2 on 2022-11-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_alter_slider_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('pk',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
